name: Update GitHub Profile Trophy

on:
  schedule:
    # Update the schedule as needed (e.g., daily, weekly)
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run GitHub Profile Trophy
        run: npx github-profile-trophy --username ne18070
